# Generated by Django 5.0.7 on 2024-10-15 00:35

import django.core.validators
import django.db.models.deletion
import feincms3.utils
import imagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accordion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Name')),
                ('toggle_close', models.BooleanField(default=False, help_text='Wether opening an item closes other open ones', verbose_name='Toggle close')),
            ],
            options={
                'verbose_name': 'Accordion',
                'verbose_name_plural': 'Accordions',
            },
        ),
        migrations.CreateModel(
            name='AccordionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Heading')),
            ],
            options={
                'verbose_name': 'Accordion item',
                'verbose_name_plural': 'Accordion items',
            },
        ),
        migrations.CreateModel(
            name='AccordionItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AccordionItem',
                'verbose_name_plural': 'AccordionItems',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagefield.fields.ImageField(height_field='height', upload_to=feincms3.utils.upload_to, verbose_name='image', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='image width')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='image height')),
                ('ppoi', imagefield.fields.PPOIField(default='0.5x0.5', max_length=20, verbose_name='primary point of interest')),
                ('alternative_text', models.CharField(blank=True, help_text='Describe the contents, e.g. for screenreaders.', max_length=1000, verbose_name='alternative text')),
                ('caption', models.CharField(blank=True, max_length=1000, verbose_name='caption')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('region', models.CharField(max_length=255)),
                ('ordering', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'rich text',
                'verbose_name_plural': 'rich texts',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='accordion',
            constraint=models.UniqueConstraint(models.F('name'), name='unique_lower_name_accordion'),
        ),
        migrations.AddField(
            model_name='accordionitemlink',
            name='accordion_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_accordion_accordion_item', to='accordion.accordionitem', verbose_name='Accordion item'),
        ),
        migrations.AddField(
            model_name='accordionitemlink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accordion.accordion'),
        ),
        migrations.AddField(
            model_name='image',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accordion.accordionitem'),
        ),
        migrations.AddField(
            model_name='richtext',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='accordion.accordionitem'),
        ),
    ]
